### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CooLowbro** [Kalafiorek/ToS-Addons#1]
Its freezing upon pressing the "Refresh All" button. :v

**Comment by CooLowbro** [comment]
Screeshoot
![image](https://user-images.githubusercontent.com/15791585/34321407-a831841c-e7f5-11e7-84ae-0e5d506eaf2f.png)

**Comment by Kalafiorek** [comment]
Looks like an language issue. It also might freeze on items that it can't read the category of (and those need to be added to a blacklist I guess). Try the "Read Market" button on the "Buy" page, it should always work.

**Comment by CooLowbro** [comment]
So, if I use it in english language, it should work?
Thanks for the fast answer! ;)

**Comment by Kalafiorek** [comment]
Can't guarantee on the "My items" scan as items added/changed by IMC could still freeze the scanning process even on english version, but the main scan on the "Buy" page should always work.

**Comment by CooLowbro** [comment]
Changing to english language worked! Thanks! <3

**Comment by CooLowbro** [comment]
I have another question. What line i should edit in order to when I press the sell button, the price on the Sell Frame goes with -1?

**Comment by Kalafiorek** [comment]
It shouldn't. Could you elaborate when does this happen? You are trying to sell an item that has it's price scanned and it changes to "-1"?

**Comment by CooLowbro** [comment]
No. This is what I want to happen.

**Comment by CooLowbro** [comment]
I want to press the Sell Button, and the price goes to the Sell Frame with -1.
Example:
Scanned 10.000 Popolion Doll
On the Sell Tab I want 9.999 Popolion Doll

**Comment by Kalafiorek** [comment]
Oh, you mean undercutting the minimal price. For the simple "-1" silver you can try "edit_price:SetText(myprice-1);" on line 743.

**Comment by CooLowbro** [comment]
Thx a lot! <3
